const fs = require('fs');
const path = require('path');

const scenarioConfigs = [
  {
    id: 'good-morning',
    emoji: '🌅',
    parts: [
      [
        'Woke up thinking about',
        'This morning reminded me that',
        'The first thing I wanted to say is',
        'My coffee is good, but',
        'Sunrise looks better when',
        'I woke up smiling because',
        'Everything feels lighter knowing',
        'The best part of today is',
        'I started my day with the thought that',
        'I hope today treats you like',
      ],
      [
        'you are my favorite beginning',
        'you make mornings feel like magic',
        'you’re the best part of today',
        'your energy is the sunshine I needed',
        'your smile is the reason the day feels right',
        'today is already better because',
        'your vibe is my morning motivation',
        'you are the warmest breakfast on my mind',
        'waking up with you in my head is everything',
        'your love is how I chose to start today',
      ],
      [
        '— go show them what you’re made of.',
        '— let’s make today unforgettable.',
        '— the world can wait for your glow.',
        '— the day already has a good story.',
        '— make it feel like a forever kind of morning.',
        '— I’m cheering for you from right here.',
        '— your vibe is already winning.',
        '— don’t forget how powerful you are.',
        '— I’m sending you extra good energy.',
        '— make every moment feel like a love note.',
      ],
    ],
  },
  {
    id: 'shes-sad',
    emoji: '🥺',
    parts: [
      [
        'It’s okay to be quiet right now,',
        'I wish I could take this weight off you,',
        'When you feel low,',
        'You don’t have to fix anything,',
        'I’m right here with you even when,',
        'If the night feels heavy,',
        'You are allowed to feel this,',
        'Your feelings are valid,',
        'I see you, especially when',
        'No matter how cloudy it gets,',
      ],
      [
        'I’m holding space for you.',
        'I want to make it softer.',
        'I’m not going anywhere.',
        'I’m listening to every word you don’t say.',
        'I still think you’re incredible.',
        'you’re still beautiful inside and out.',
        'I’m here for the slow moments too.',
        'you are loved even on the hard days.',
        'your heart matters more than anything else.',
        'I’m right here if you need me.',
      ],
      [
        'Let me know how I can help.',
        'There’s no rush to feel okay.',
        'Come sit with me for a minute.',
        'We can breathe through it together.',
        'Your peace matters more than perfection.',
        'I love you, no matter what.',
        'You’re stronger than this day feels.',
        'I’m here for you with all of me.',
        'I can wait while you heal.',
        'I’m on your team forever.',
      ],
    ],
  },
  {
    id: 'you-messed-up',
    emoji: '💀',
    parts: [
      [
        'I messed up today,',
        'That one was on me,',
        'I dropped the ball,',
        'I made a mistake and I’m sorry,',
        'I should have handled that better,',
        'I want to own this,',
        'This one is my fault,',
        'I know I hurt you,',
        'I get why you’re upset,',
        'I blew it and I’m sorry,',
      ],
      [
        'and I want to fix it.',
        'and I’ll do better.',
        'I’m genuinely sorry.',
        'I see where I went wrong.',
        'and I don’t want to let it slide.',
        'I’m learning from it.',
        'please let me make it right.',
        'I hope you can give me another chance.',
        'I know I owe you better.',
        'I want to be someone you deserve.',
      ],
      [
        'Thank you for being patient with me.',
        'I’m here until you feel okay again.',
        'I’m ready to listen to how you feel.',
        'You deserve the truth and my best effort.',
        'I’ll make this right with actions, not just words.',
        'I’m committed to showing up better.',
        'I care about how this made you feel.',
        'I appreciate you and I’m sorry.',
        'My heart is with you on this.',
        'I love you and I’m sorry.',
      ],
    ],
  },
  {
    id: 'random-affection',
    emoji: '💕',
    parts: [
      [
        'You’re the part of today that keeps making me smile,',
        'I keep finding new reasons to love you,',
        'When I think of everything good,',
        'You make the ordinary feel special,',
        'You’re my favorite hello and hardest goodbye,',
        'I’m grateful for the way you exist,',
        'Your laugh is the highlight of my day,',
        'I love how real you are,',
        'The way you move through the world is everything,',
        'You’re the reason I believe in lucky days,',
      ],
      [
        'and I want you to know that.',
        'and I don’t know what I did to deserve you.',
        'and it makes my heart full.',
        'and I’m still not over you.',
        'and I hope you feel how much I care.',
        'and I’m thinking about you right now.',
        'and I’m so proud to be with you.',
        'and I wish you could see yourself through my eyes.',
        'and it makes everything better.',
        'and it’s why I can’t stop smiling.',
      ],
      [
        'Just in case you needed to hear it today.',
        'You’re my favorite part of every day.',
        'I love you a little more every moment.',
        'You’re my forever mood.',
        'Believe me when I say that.',
        'I’m totally into you.',
        'Nothing beats the way you are.',
        'I’m sending that energy back to you.',
        'You deserve all of this love.',
        'You’re the best thing in my life.',
      ],
    ],
  },
  {
    id: 'miss-you',
    emoji: '💭',
    parts: [
      [
        'I miss the way your laugh sounds,',
        'Everything feels quieter without you,',
        'I keep replaying the last time we were together,',
        'The space beside me still feels yours,',
        'I can’t stop thinking about your smile,',
        'I miss our random little moments,',
        'My phone feels empty when you’re gone,',
        'The world is missing a little brightness without you,',
        'I wish I could rewind to the last time I held you,',
        'I’m counting the moments until I see you again,',
      ],
      [
        'and it makes me want you even more.',
        'and I’m already planning the next time.',
        'and I can’t wait to be close again.',
        'and it feels like the day is missing a color.',
        'and I hope you know that.',
        'and I’m sending you all my love from here.',
        'and it makes my heart ache in a good way.',
        'and I’m wishing you were here.',
        'and I’m holding onto the next hello.',
        'and it feels like a quiet song without you.',
      ],
      [
        'I miss you more than words can say.',
        'See you soon, okay?',
        'Come back to me soon.',
        'I’m keeping you in every thought.',
        'I’m saving my best moments for you.',
        'I’m here whenever you’re ready.',
        'I hope you’re feeling the same pull.',
        'You’re the best part of every memory.',
        'I love missing you because it means I’m loving you.',
        'I’m already planning how to make the next time better.',
      ],
    ],
  },
  {
    id: 'date-ideas',
    emoji: '🌸',
    parts: [
      [
        'Let’s turn tonight into a cozy movie picnic,',
        'How about a sunset walk with your favorite playlist,',
        'I want us to explore a new coffee spot,',
        'What if we took a spontaneous drive and got lost together,',
        'Let’s make dinner together and eat on the balcony,',
        'We should find a rooftop and watch the city lights,',
        'I want a slow morning with pancakes and you,',
        'How about a thrift store adventure followed by ice cream,',
        'Let’s make a playlist and dance in the kitchen,',
        'We could write each other letters and read them out loud,',
      ],
      [
        'then end the night with stars.',
        'and talk about anything and everything.',
        'and see where the evening takes us.',
        'and keep it all low-key and sweet.',
        'and make it one of those nights we remember.',
        'and let the world fall away for a bit.',
        'with no plans except to enjoy each other.',
        'and celebrate just being together.',
        'and make the simplest thing feel unforgettable.',
        'and let our laughter lead the way.',
      ],
      [
        'I promise it’ll be worth the time.',
        'I’ll bring the snacks.',
        'Let’s make it ours.',
        'I want to make you smile all night.',
        'You pick the song and I’ll handle the rest.',
        'This one’s all about us.',
        'It’ll be the best kind of easy.',
        'I already know it’ll be perfect with you.',
        'We can keep it simple and still feel magic.',
        'Let’s make it a night we talk about forever.',
      ],
    ],
  },
  {
    id: 'compliments',
    emoji: '✨',
    parts: [
      [
        'You have this way of making everything feel better,',
        'Your confidence is quietly dangerous,',
        'The way you show up is inspiring,',
        'Your kindness makes the whole room softer,',
        'You make real look effortless,',
        'Your laugh is the kind I want on repeat,',
        'Your presence is the best kind of distraction,',
        'You’re the kind of person I want on my team,',
        'The way you care is rare,',
        'You’re the person everyone wants in their corner,',
      ],
      [
        'and it’s one of the things I love most.',
        'and it makes me proud to be by your side.',
        'and it reminds me why I’m here.',
        'and I’m grateful for it every day.',
        'and it’s one of the best parts of knowing you.',
        'and I can’t help but notice it.',
        'and it makes me want to be better too.',
        'and I hope you see it in yourself.',
        'and it’s absolutely magnetic.',
        'and it makes my heart full.',
      ],
      [
        'You deserve every compliment and more.',
        'Never doubt how amazing you are.',
        'I’m obsessed with how real you are.',
        'You’re doing it better than you realize.',
        'Keep being exactly who you are.',
        'You’re simply unforgettable.',
        'That’s your superpower.',
        'You’re someone I look up to.',
        'You shine in a way only you can.',
        'You’re the kind of amazing that doesn’t fade.',
      ],
    ],
  },
  {
    id: 'apologies',
    emoji: '🥀',
    parts: [
      [
        'I’ve been thinking about what happened,',
        'I owe you a real apology,',
        'I know I hurt you,',
        'I didn’t mean to make you feel that way,',
        'I want to be better for you,',
        'I know I let you down,',
        'What I said was wrong,',
        'I should have listened more,',
        'I’m sorry for not being there when you needed me,',
        'I regret how I handled that,',
      ],
      [
        'and I’m sorry from the bottom of my heart.',
        'and I want to fix it.',
        'and I don’t want to lose what we have.',
        'and I’m learning from it.',
        'and I want you to feel respected.',
        'and I hope you can forgive me.',
        'and I’m going to do better.',
        'and I value you more than that mistake.',
        'and I’m here to listen to you.',
        'and I’ll take responsibility for it.',
      ],
      [
        'Please let me make it right.',
        'I love you and I’m sorry.',
        'I want to rebuild that trust.',
        'Thank you for giving me another chance.',
        'I’m committed to growing from this.',
        'I care so much about you.',
        'Your feelings matter more than my ego.',
        'I’m sorry and I mean it.',
        'I won’t make the same mistake again.',
        'I’m here until you feel okay again.',
      ],
    ],
  },
  {
    id: 'goodnight',
    emoji: '🌙',
    parts: [
      [
        'Goodnight, my favorite part of the day,',
        'Sleep well knowing I’m thinking of you,',
        'The night feels softer with you in my thoughts,',
        'I hope your dreams are as sweet as you are,',
        'Rest easy, you deserve the best sleep,',
        'I’m sending you calm thoughts and warm wishes,',
        'Close your eyes knowing you’re loved,',
        'I can’t wait for the morning to say good morning again,',
        'The stars are quiet, but I’m still thinking of you,',
        'End the day knowing you’re the last thing on my mind,',
      ],
      [
        'and I’ll be here when you wake up.',
        'I’ll see you in my dreams.',
        'I hope you wake up feeling rested.',
        'I’m holding you in my heart tonight.',
        'I’m grateful for you today and always.',
        'Take it easy and let yourself recharge.',
        'I’m already looking forward to tomorrow with you.',
        'You matter so much to me.',
        'Your peace is my favorite thing to wish for.',
        'I’m sending you a gentle hug through this message.',
      ],
      [
        'Goodnight, love.',
        'See you in the morning.',
        'Sleep tight, beautiful.',
        'Rest up, my love.',
        'Sweet dreams, my favorite person.',
        'I’ll be here when you wake up.',
        'Night night, stay cozy.',
        'Dream about the next time we’re together.',
        'All my love tonight.',
        'Goodnight, you’re my peace.',
      ],
    ],
  },
  {
    id: 'just-because',
    emoji: '🎀',
    parts: [
      [
        'I saw something that reminded me of you,',
        'I just wanted you to know,',
        'There’s no reason except that I miss you,',
        'I’m thinking about how lucky I am,',
        'You crossed my mind and I smiled,',
        'This is just a random love note,',
        'I wanted to brighten your day,',
        'I’m sending you a little extra affection,',
        'I want you to feel loved right now,',
        'You’re on my mind for no reason other than you’re amazing,',
      ],
      [
        'and it made me want to tell you.',
        'and I couldn’t keep it to myself.',
        'and I hope it makes you smile.',
        'and I hope you feel as special as you are.',
        'and I want you to know I’m here.',
        'and I hope your day gets even better.',
        'and I’m grateful for you always.',
        'and I’m sending you warm thoughts.',
        'and I’m thinking of all the little reasons I love you.',
        'and I hope it reminds you that you matter.',
      ],
      [
        'You’re amazing, just because.',
        'You deserve all the good things.',
        'I appreciate you more than you know.',
        'I’m lucky to have you.',
        'You make my life better just by being you.',
        'Keep being incredible.',
        'I love you just because.',
        'You make the ordinary feel special.',
        'Thank you for being you.',
        'I’m so glad you exist.',
      ],
    ],
  },
];

function generateIdeas() {
  const ideas = [];
  const targetPerScenario = 3000;

  for (const scenario of scenarioConfigs) {
    const [partA, partB, partC] = scenario.parts;
    const total = targetPerScenario;

    for (let index = 0; index < total; index += 1) {
      const a = partA[index % partA.length];
      const b = partB[Math.floor(index / partA.length) % partB.length];
      const c = partC[Math.floor(index / (partA.length * partB.length)) % partC.length];
      const text = `${a} ${b} ${c}`.replace(/\s+/g, ' ').trim();
      ideas.push({
        id: `${scenario.id}-${String(index + 1).padStart(4, '0')}`,
        category: 'texts',
        scenario: scenario.id,
        text,
        emoji: scenario.emoji,
      });
    }
  }

  return ideas;
}

const ideas = generateIdeas();
const outputPath = path.resolve(__dirname, '../src/data/ideas.json');
fs.writeFileSync(outputPath, JSON.stringify(ideas, null, 2));
console.log(`Generated ${ideas.length} ideas to ${outputPath}`);
